# ConfigMap for uwsgi
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-uwsgi
  labels:
    project: {{ .Chart.Name }}
    app: {{ .Chart.Name }}-uwsgi
    name: {{ .Chart.Name }}-uwsgi
    githash: {{ .Values.deploy.imageTag | quote }}
data:
  uwsgi.yaml: |-
    uwsgi:
      uid: aladdin-user
      gid: aladdin-user

      master: true
      processes: {{ .Values.app.uwsgi.processes }}

      buffer-size: {{ .Values.app.uwsgi.bufferSize }}
      socket: :{{ .Values.app.uwsgi.port }}
      py-autoreload: {{ .Values.app.uwsgi.autoreload }}

      wsgi-file: run.py
      callable: app

      enable-threads: true
      die-on-term: true

      harakiri: {{ .Values.app.uwsgi.harakiri }}
      harakiri-verbose: true

      disable-logging: {{ .Values.app.uwsgi.disableLogging }}

      logformat: %(ftime) %(status) %(method) %(uri)
      logformat-strftime: true
      log-date: %%H:%%M:%%S

      route: ^/app/ping donotlog:
